# This file has been generated by mavenix-2.3.2. Configure the build here!
{ pkgs    ? (import ./nix {}).pkgs { inherit system; }
, mavenix ? pkgs.mavenix
, src     ? { outPath = ./.; }
, system  ? builtins.currentSystem
, doCheck ? false }: let

  self = mavenix.buildMaven {
    inherit doCheck;
    infoFile = ./mavenix.lock;
    src = pkgs.gitignoreSource src;

    # Add build dependencies
    #
    buildInputs = with pkgs; [ makeWrapper ];
    pname = "hoc2js";

    # Set build environment variables
    #
    #MAVEN_OPTS = "-Dfile.encoding=UTF-8";

    # Attributes are passed to the underlying `stdenv.mkDerivation`, so build
    #   hooks can be set here also.
    #
    postInstall = ''
      makeWrapper ${pkgs.jre8_headless}/bin/java $out/bin/${self.pname} \
        --add-flags "-jar $out/share/java/${self.name}.jar"
    '';

    # Add extra maven dependencies which might not have been picked up
    #   automatically
    #
    #deps = [
    #  { path = "org/group-id/artifactId/version/file.jar"; sha1 = "0123456789abcdef"; }
    #  { path = "org/group-id/artifactId/version/file.pom"; sha1 = "123456789abcdef0"; }
    #];

    # Add dependencies on other mavenix derivations
    #
    #drvs = [ (import ../other/mavenix/derivation {}) ];

    # Override which maven package to build with
    #
    #maven = maven.overrideAttrs (_: { jdk = pkgs.oraclejdk10; });

    # Override remote repository URLs and settings.xml
    #
    #remotes = { central = "https://repo.maven.apache.org/maven2"; };
    #settings = ./settings.xml;
}; in self
#}; in self.overrideAttrs (o: {
#  buildInputs = with pkgs; [ makeWrapper ];
#  postInstall = ''
#    makeWrapper ${pkgs.jre8_headless}/bin/java $out/bin/${o.pname} \
#      --add-flags "-jar $out/share/java/${o.name}.jar"
#  '';
#})
